name: Flutter

on:
  push:
    branches: [ "dnd-22" ]
  pull_request:
    branches: [ "dnd-22" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6'
          channel: 'stable'

      - name: Checking version
        run: flutter --version

      - name: Installing dependencies
        run: flutter pub get

      - name: Building web app
        run: flutter build web --release --no-tree-shake-icons

      - name: Deploy settings up
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./build/web

      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@v12.9.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
